### ISSUE TITLE
Occasional panic writing to websocket

### ISSUE THREAD

**Issue by gnarf** [Prime-Access-Consulting/nvda-at-automation#50]
I saw this one other time, but wasn't setup to capture the log.  This error occasionally happens and will stop the server / automation from continuing.

```
2024/05/06 07:38:14 Received command interaction.pressKeys
panic: concurrent write to websocket connection

goroutine 19 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc000461c50, 0x1, {0xc000426c7b?, 0x10?, 0x60bde0?})
        C:/Users/gnarf/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:617 +0x4b8
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc0001542c0, 0x22?, {0xc000426c00, 0x7b, 0x80})
        C:/Users/gnarf/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:770 +0x127
Server/server.(*Server).sendMessage(...)
        F:/Code/aria-at/nvda-at-automation/Server/server/server.go:70
Server/server.(*Server).handleNewSessionCommand.func2.1({0xc00009c1f0?, 0xc0004f3010?, 0xc00009c350?})
        F:/Code/aria-at/nvda-at-automation/Server/server/server.go:114 +0x91
Server/sse.(*Parser).tryDispatchEvent(0xc000461f98)
        F:/Code/aria-at/nvda-at-automation/Server/sse/eventstream.go:69 +0x42
Server/sse.(*Parser).Process(0xc0004f2aa8?, {0xc0004f2aa8, 0x7})
        F:/Code/aria-at/nvda-at-automation/Server/sse/eventstream.go:58 +0x1a5
Server/client.(*NVDA).RegisterOnLineCallback(0xc00004a4c0, 0xc000461fa8)
        F:/Code/aria-at/nvda-at-automation/Server/client/client.go:253 +0x4e5
Server/server.(*Server).handleNewSessionCommand.func2()
        F:/Code/aria-at/nvda-at-automation/Server/server/server.go:121 +0x7e
created by Server/server.(*Server).handleNewSessionCommand in goroutine 18
        F:/Code/aria-at/nvda-at-automation/Server/server/server.go:124 +0x291
```

**Comment by jscholes** [comment]
@gnarf / @jugglinmike I've just pushed a fix for this issue.  Please let me know if you run into it again, or if the change causes any unexpected side effects, as I can't currently carry out an end-to-end automation run myself.
